<a href="https://colab.research.google.com/github/Beepboop-B/ML/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())


2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_arr=np.zeros(10,1)
print(null_arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(null_arr.itemsize)
print(null_arr.size)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_arr2=np.zeros(10)
null_arr2[4]=1
print(null_arr2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr1=np.empty(40,dtype=np.int64)
'''default type is flaot64'''
for i in range(40):
  arr1[i]=(i+10)
print(arr1)
'''or'''
arr2=np.arange(10,50)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr3=np.arange(1,10)
arr3=arr3[::-1]
print(arr3)

[9 8 7 6 5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr4=np.arange(0,9).reshape(3,3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
ex_arr=np.array([1,2,0,0,4,0])
print(np.nonzero(ex_arr))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
iden3x=np.eye(3,3)
'''or np.identity(3)'''
print(iden3x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
ndarr= np.random.randint(1,10,(3,3,3))
print(ndarr)

[[[7 2 4]
  [2 9 3]
  [4 6 2]]

 [[8 1 1]
  [9 9 8]
  [5 6 1]]

 [[3 2 9]
  [8 6 2]
  [6 7 6]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr10_=np.random.randint(0,100,(10,10))
print(arr10_)
print(arr10_.max())
print(arr10_.min())
print(np.where(arr10_==0))

[[83 93 34  0 35 23 22 99 38  8]
 [36 30 26 24 36 83 27  0 30 88]
 [89 51 61 55 36 67 83 48  3 23]
 [16 99 47 78  7 34 64  1 42 93]
 [77 95 75 43  7 90 77 76 64 18]
 [69 84 65 53 96 60 30 70 20 13]
 [ 6  3  0 95 79 21 67  0 12 59]
 [53 36 52 87 60 19 15 99 56 57]
 [22  8 91 77  2 51 45 61  1 17]
 [77  2 96 35 69 19 11 14 54 15]]
99
0
(array([0, 1, 6, 6]), array([3, 7, 2, 7]))


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr30=np.random.randint(0,50,(30))
print(arr30.mean())

24.533333333333335


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr2d=np.ones((5,5), dtype = int)
arr2d[1:-1,1:-1]=0

print(arr2d)



[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arrdt=np.random.randint(1,11,(5,5))
arrdt[0,:]=0
arrdt[-1,:]=0
arrdt[:,0]=0
arrdt[:,-1]=0
print(arrdt)

[[0 0 0 0 0]
 [0 5 9 6 0]
 [0 4 7 5 0]
 [0 3 7 5 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [9]:
arr = [1,2,3,4,5]


python_sum_result = sum(arr)
sum1 = np.sum(arr)
print(python_sum_result)
print(sum1)

15
15


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [10]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print(np.array_equal(a,b))

True


#### 43. Make an array immutable (read-only) (★★☆)

In [11]:
imm=np.array([1,2,3,4,5])
imm.flags.writeable=False
# imm[0]=10
print(imm)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [13]:
arrcart=np.arange(1,21).reshape(10,2)
print(arrcart)
x=arrcart[:,0]
y=arrcart[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[ 2.23606798  5.          7.81024968 10.63014581 13.45362405 16.2788206
 19.10497317 21.9317122  24.75883681 27.58622845]
[1.10714872 0.92729522 0.87605805 0.85196633 0.83798123 0.82884906
 0.82241828 0.81764505 0.81396182 0.81103357]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [24]:
randarr_=np.random.rand(10)
print(randarr_)
randarr_[randarr_.argmax()]=0
print(randarr_)


[0.26978333 0.41281552 0.03258709 0.42796804 0.46855015 0.74453902
 0.83431597 0.38855677 0.24829776 0.78868944]
[0.26978333 0.41281552 0.03258709 0.42796804 0.46855015 0.74453902
 0.         0.38855677 0.24829776 0.78868944]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [31]:
arr5_ = np.array([[1,2],
                [3,4]])

for index, value in np.ndenumerate(arr5_):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [32]:
import numpy as np

size = 100
x = np.linspace(-1, 1, size)
y = np.linspace(-1, 1, size)

X, Y = np.meshgrid(x, y)

sigma = 0.3

gaussian = (1 / (2 * np.pi * sigma**2)) * \
           np.exp(-(X**2 + Y**2) / (2 * sigma**2))

print(gaussian)

[[2.64291611e-05 3.30052796e-05 4.10311856e-05 ... 4.10311856e-05
  3.30052796e-05 2.64291611e-05]
 [3.30052796e-05 4.12176716e-05 5.12405879e-05 ... 5.12405879e-05
  4.12176716e-05 3.30052796e-05]
 [4.10311856e-05 5.12405879e-05 6.37007805e-05 ... 6.37007805e-05
  5.12405879e-05 4.10311856e-05]
 ...
 [4.10311856e-05 5.12405879e-05 6.37007805e-05 ... 6.37007805e-05
  5.12405879e-05 4.10311856e-05]
 [3.30052796e-05 4.12176716e-05 5.12405879e-05 ... 5.12405879e-05
  4.12176716e-05 3.30052796e-05]
 [2.64291611e-05 3.30052796e-05 4.10311856e-05 ... 4.10311856e-05
  3.30052796e-05 2.64291611e-05]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [35]:
arr2d=np.array([[1,2,3,4,5],
                [6,7,8,9,0]])
p=5
indices=np.random.choice((arr2d.size),p,replace=False)
# arr2d.ravel()[indices]=0 or
arr2d.flat[indices] = 1
print(arr2d)

[[1 2 3 1 5]
 [1 1 1 9 1]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [28]:
arr2d=np.array([[1,2,3,4,5],
                [6,7,8,9,0]])
arr2d=arr2d-arr2d.mean(axis=1,keepdims=True)
print(arr2d)

[[-2. -1.  0.  1.  2.]
 [ 0.  1.  2.  3. -6.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [27]:
arr2d=np.array([[1,2,3,4,5],
                [6,7,8,9,0]])
arr2d=arr2d[:,arr2d[1,:].argsort()]
print(arr2d)

# Sort rows by column n	 -------->   arr[arr[:, n].argsort()]
# Sort columns by row n	 -------->   arr[:, arr[n, :].argsort()]

[[1 2 3 4 0]
 [6 7 8 9 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [26]:
arr2d=np.array([[1,2,3,4,5],
                [6,7,8,9,0]])
print(np.all(arr2d,axis=0))

[ True  True  True  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)